version: "2"
services:
  # POSTGRES
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    image: postgis/postgis:11-3.1-alpine
    environment:
      POSTGRES_PASSWORD: gfspass
      POSTGRES_USER: gfs
  # PHPPGADMIN
  phppgadmin:
    ports:
      - "8081:80"
    image: dockage/phppgadmin:latest
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=postgres

volumes:
  postgres: